#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    local subdomain="$2"
    local domain="$1"
    local result
    result=$(dig "$subdomain.$domain" +short)
    
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    else
        echo "The subdomain $subdomain does not have a valid A record"
    fi
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
