#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#
# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

# Update the package repository and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define the hostname based on the machine's hostname
hostname=$(hostname)

# Create a custom Nginx configuration file for redirection
cat <<EOF | sudo tee /etc/nginx/conf.d/3-redirection.conf
server {
    listen 80;
    server_name _;

    # Define the location for redirection
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Include additional Nginx configuration files
    include /etc/nginx/sites-enabled/*;
}
EOF

# Remove the default configuration symlink
sudo rm -f /etc/nginx/sites-enabled/default

echo -e "\n${bleu} Restart Nginx to apply the changes.${reset} \4n" 
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
