#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
aENABLED="ENABLED=1"
sudo sed -i -e "\$aENABLED\n" /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 192264-web-01 3.85.41.154:80 check\n\tserver 192264-web-02 34.207.63.227:80 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
