#!/usr/bin/env bash
# Your Bash script configures a new Ubuntu machine to match the task requirements

# Update the package list and upgrade installed packages
sudo apt-get update
sudo apt-get upgrade -y

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo touch /etc/haproxy/haproxy.cfg

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 54.144.137.166:80 check
    server web-02 52.87.220.107:80 check

EOF

# Verify HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Enable and start HAProxy as a service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Ensure HAProxy is added to the init script
sudo update-rc.d haproxy defaults

# Update the hostname of the server
sudo hostnamectl set-hostname 192264-lb-01

# Reboot to apply changes
sudo service haproxy restart

